### ISSUE TITLE
Does not populate slash command options list

### ISSUE THREAD

**Issue by randomairborne** [baptiste0928/twilight-interactions#19]
When using an enum of valid slash command options, like in [card.rs](https://github.com/randomairborne/experienced/blob/399eab0582f3914d7345d1be0e48f4e82380c7af/slash/src/cmd_defs/card.rs#L41), I do not see the required command options populating in the discord command picker.

**Comment by baptiste0928** [comment]
Hello ! The `CommandEditFont` doesn't seem to be used anywhere in your code. You also need to derive [`CreateOption`](https://docs.rs/twilight-interactions/latest/twilight_interactions/command/trait.CreateOption.html) on the enum to be able to register commands using it.

**Comment by randomairborne** [comment]
Oh no! I entirely didn't notice that. I'm very sorry.
