### ISSUE TITLE
`CreateCommand`'s `#[command(desc = ...)` attribute does not trim spaces from the string during length validation

### ISSUE THREAD

**Issue by fridenity0777** [baptiste0928/twilight-interactions#23]
### Summary
When deriving a struct with `CreateCommand` and adding `#[command(desc = ...)` to either structs representing commands or fields of said structs representing command options, it performs a string length validation on the `desc` attribute, but it does not trim spaces from the string before the doing so.

It seems like either Twilight under the hood or the Discord API itself is trimming spaces in the description field of commands and command options, and the macro should follow this system.

### Steps to reproduce
1. Define a struct representing the command, and leave the `desc` attribute of either the command itself or the field to be blank spaces:
```rs
...
#[derive(CreateCommand)]
#[command(name = "test-command", desc = " ")]
pub struct TestCommand {
    #[command(desc = " ")]
    option: int,
}
...
```
2. Create the command, declare it, and compile the program.

### Expected Result
The program should fail to compile with the error either stating that the `desc` provided was not between 1-100 characters or giving a more detailed message regarding having spaces in the string and how it will be trimmed by the Discord API anyways.

### Actual Result
The program compiles, but after the command declaration, exits with the following error message:
```rs
Error: Response error: status code 400, error: {"code": 50035, "errors": {"3": {"options": {"0": {"options": {"2": {"options": {"0": {"description": {"_errors": [{"code": "BASE_TYPE_BAD_LENGTH", "message": "Must be between 1 and 100 in length."}]}}}}}}}}}, "message": "Invalid Form Body"
```

### Additional Info
- The spaces in `desc` are trimmed regardless of how many spaces there were; Putting a string with only 100 spaces as `desc` would still be trimmed to an empty string, resulting in the same exiting error.
- `twilight-interactions` Version: `0.15.1`
- `twilight` Version: `0.15.0`

**Comment by baptiste0928** [comment]
Thanks for the detailed report! I fixed this, I will be available with the next update.
