### ISSUE TITLE
Twilight 0.16 Support

### ISSUE THREAD

**Issue by fdnt7** [baptiste0928/twilight-interactions#34]
Hello. `twilight` has announced their first release candidate of `0.16`, which changed a lot of re-exports, names and structures of many models in `twilight-model`, particularly the interactions-related models. This made `twilight-interactions` unusable with `=0.16.0-rc.1`.

I wanted to ask if there have been any ongoing efforts to update this library to `twilight` `0.16`.
If not, I've [forked](https://github.com/fdnt7/twilight-interactions/tree/feat/twilight-0.16) this repository and updated the library (including the example bot) to `twilight` `=0.16.0-rc.1`. I've tested using the forked library with my bot and encountered no issues so far.

I'm more than happy to submit a PR to this repository, so please let me know what you think. Thank you in advance.

**Comment by baptiste0928** [comment]
No work has been started yet to update to twilight 0.16, your PR is very welcome. Thanks for your initiative!
