### ISSUE TITLE
allow other integer types like u8 depending on the min/max values

### ISSUE THREAD

**Issue by laralove143** [baptiste0928/twilight-interactions#6]
so in an option like
```rust
#[command(desc = "foo", min_value = 1, max_value = 20)]
num_option: i64
```
isn't it unnecessary to use `i64` since the value cant overflow?

**Comment by baptiste0928** [comment]
It would be possible to allow other integer types depending on the attributes, but this would require a more complex validation at the macro level.

I don't think it's worth it to make them more complex when a simple cast does the job. Is it really annoying for you to use only `i64`?

**Comment by laralove143** [comment]
no not really, i guess i was asking for microoptimization purposes 😰

**Comment by baptiste0928** [comment]
If you really wants to avoid using i64s, it is possible to create two structs for the command, one that implement `CommandModel` and the other that will be used in the rest of your code. This allows to perform an additional validation step, since you parse the Discord interaction in the first type, and convert this type to the other one with a custom function where you can make the wanted validations and transformations.

```rust
/// This type will be used in the rest of your code.
struct MyCommand {
    num_option: u8,
}

/// This type is the "raw" model used to parse Discord interactions.
#[derive(CommandModel)]
struct MyCommandModel {
    #[command(min_value = 1, max_value = 20)]
    num_option: i64,
}

// Add a function to convert MyCommandModel to MyCommand (and maybe perform additional validations)
```

**Comment by laralove143** [comment]
oh yes ofc but i was asking for a change in the library

**Comment by baptiste0928** [comment]
The current implementation requires that all types used in command models implement `CommandOption`, regardless of the attributes used. Adding support for other integer types is thus not compatible with this.

This could be changed, but it would certainly complicate the functioning of the library. Being limited to one type of integer is not a significant problem, as it is easy to cast to another integer type if needed, and it has almost no performance impact.
